require_relative 'piece'
require_relative 'pawn'
require_relative 'rook_bishop_queen'
require_relative 'knight_king'
require_relative 'nullpiece'
require_relative 'stepable'
require_relative 'slideable'
